# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_buy_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseclass',
            options={'verbose_name_plural': '课程第一分类'},
        ),
        migrations.AlterModelOptions(
            name='coursesort',
            options={'verbose_name_plural': '课程第二分类'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': '课程章节信息'},
        ),
    ]
